### ISSUE TITLE
Stuff to do for v0.5.2

### ISSUE THREAD

**Issue by kitskub** [kitskub/MyHungerGames#14]
- (check) Make it so spawns can look around
- (check) Autosubscribe permission
- (check) (needs testing) Fix files
- (check) Indexoutofbounds at com.randude14.hungergames.games.HungerGame.checkForGameOver(HungerGame.java:869)
- (unconfirmed) % instead of the game name in quit
- (check) Add catch for /hga set fixedchest
- (pushed) Add chests to internal listening w/config option
- (pushed) Have a way for players to teleport back to where they were before the game
- (check) auto-vote logic is wrong. Does not count as a vote except in count, so can't cause an auto-start.
- (done already) Listen for leaves despawning
- (pushed) Maybe add some way for worlds to reset while games are not running

**Comment by Bjornke** [comment]
Not understanding what "% instead of the game name in quit" this means. Would % replace the name of the game you're trying to quit from??

EDIT: never-mind figured it out.

**Comment by Bjornke** [comment]
I just pushed an update that fixes IndexOutOfBounds by checking if remaining isEmpty or not. Also made it so users can look around and jump at spawn, but still cannot leave spawn.
