### ISSUE TITLE
Restock Chests

### ISSUE THREAD

**Issue by illumi241** [kitskub/MyHungerGames#15]
Don't know if it is there and isn't working or if it doesn't exist.

It would be nice if the Chests are automatically refilled with the original content without commands or something. On my Server it isnt even working WITH commands, don't know what's wrong.
Logblock is activated on this world and allmost everything is logged incuding chest acces.
An Alternative to use LogBlock would be to store the Chest contents in a sql Database, maybe even changable over a Webinterface then ;-)

I would like if the restock function would work at all, because if a game ends, the Chests are empty in a new game, so that an Admin has to refill the Chests manually after every Game. And yes, i know that there is a command, but it just doesn't work for me, no errors, nothing, just doesn't work. No message in console and no reply in chat.

**Comment by kitskub** [comment]
This has been fixed in the latest builds.
