### ISSUE TITLE
"Tournament is already full" Bugged Error

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#18]
The tournament is Empty, but for some reason, when trying /hg join Tournament, it states, that it is full. It's EMPTY. There no participants in tournament.
http://pastie.org/private/oqqupgzhon3v8ywttujf7g

**Comment by WoAnerges** [comment]
Possibly fixed with a new beta update. Confirmed, that error does not appear with the latest build anymore.

**Comment by WoAnerges** [comment]
Re-opened. Problem is still there. It happens after performing 3 steps:
1. /hga set enabled Hunger false
2. /hga set enabled Hunger true
3. /hga reload

**Comment by kitskub** [comment]
The problem is /hga reload. I THINK I have fixed this in the latest builds

**Comment by WoAnerges** [comment]
This error is still happening on 0.7-dev-082620122041

**Comment by kitskub** [comment]
I believe I have fixed this.
