### ISSUE TITLE
Tournament Already Exist \ Don't exist

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#21]
When I try to remove a tournament, it says "Tournament Don't Exsist", so I'm trying re-creating it again, but then it says "Already Exist".

Can this plugin make up it's mind?

**Comment by WoAnerges** [comment]
:)

**Comment by kitskub** [comment]
Are you using the latest version? (actually the second to latest version at this exact time because the latest is broke)

I'm not sure if I fixed this. It's a very odd occurence that happens very rarely.

**Comment by WoAnerges** [comment]
This is happened, when I used the official release of your's.

**Comment by kitskub** [comment]
Can you try this build: https://github.com/kitskub/MyHungerGames/blob/748e05379f16eb40447c59152a3c492f5a63f7e1/target/MyHungerGames-0.7-dev-082020120941.jar?raw=true

**Comment by WoAnerges** [comment]
This particular problem, looks like, disappeared.
Thank you.
