### ISSUE TITLE
Few complications with items

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#25]
#1 First problem is after player dies, all items, that he found staying with him. I confirmed it. Several players were reporting this.

But, probably, it is because my parameter clear-inv is set to false?
#2 Another problem is that "remove-items: true", I assume, it removes items before game begins. However, players are still starting with items.

But, probably, it is because my parameter require-inv-clear is set to false?

It is, probably, just my misunderstanding of the config.

Thank you.

**Comment by kitskub** [comment]
Yes, clear-inv has MyHungerGames clear the inventory and save it. require-inv-clear makes the players clear their inventory before joining. Remove-items removes items on the ground after the game ends.

**Comment by WoAnerges** [comment]
Thank you.
