### ISSUE TITLE
MyHungerGames is causing a HUGE server lagg

### ISSUE THREAD

**Issue by WoAnerges** [kitskub/MyHungerGames#30]
MyHungerGames is causing a HUGE server lagg and lagg is so big, that sometimes, server just hangs for few minutes.
It's usually happening after the game has ended. But it's happening always.

**Comment by kitskub** [comment]
It could be the rollback that is happening at the end. I'm not sure about what else it could be, I have run profiles and found nothing.

**Comment by WoAnerges** [comment]
lagg starts after I try /hga reload, /hga set enable Tournament true and few other commands. Sending hga commands may cause temporary server freezing sometimes. Can't help, but feel, there's loophole somewhere, or something.
Please, add me on skype "*******", I will give you address to my server and we will test it together.

**Comment by kitskub** [comment]
Will do. I edited out your skype name so you don't recieve spam and stuff

**Comment by WoAnerges** [comment]
Thanks, kitskub.

**Comment by kitskub** [comment]
Can you confirm this is still happening?

**Comment by WoAnerges** [comment]
Unable to confirm.

**Comment by kitskub** [comment]
Like, it doesn't happen or you can't test?

**Comment by Trikolon** [comment]
Seems similar to #44

**Comment by Trikolon** [comment]
Are these rollbacks processed in a seperate thread?

**Comment by Trikolon** [comment]
Seems to be fixed in latest dev-build.
