### ISSUE TITLE
ChestLoot Problems

### ISSUE THREAD

**Issue by KadianK4** [kitskub/MyHungerGames#32]
The answer to this is probably really simply. But, I don't have much experience with plugins, and or the yml's that the plugins require.

I can't get my chests to fill with random items for the life of me, they are all added to the game that I've titled "Hunger" but, they don't seem to fill with anything. At one point we got them to fill with cobwebs. But, we couldn't figure out how we did that.

Simply, could anyone provide a small tutorial on how to get the chests to fill with loot? Or just tell me what I need to do to get them to start generating random loot please.

Thanks in advance.

**Comment by kitskub** [comment]
I cannot reproduce this problem. Besides, the itemconfig.yml is being written, so this bug will be obsolete.
