### ISSUE TITLE
Chest causes server crash.

### ISSUE THREAD

**Issue by ghost** [kitskub/MyHungerGames#36]
Everything works fine with people joining the game, and people starting the game, and even killing eachother. The only problem is when someone, while in a hunger games match, opens a chest. It crashes the server. Everything freezes for like 20 seconds to a minute. And then crashes.
Is there some way to fix this?

**Comment by CblaProf** [comment]
Yes, this happens every time with me too, and not just crash, it totally hands the server thread which crashes after 30 seconds or so.

**Comment by kitskub** [comment]
Fixed.
