### ISSUE TITLE
Client Connection Error after Game End

### ISSUE THREAD

**Issue by kkieslich** [kitskub/MyHungerGames#44]
Hello,
i want to report the bug, which appears after a Game ends.
The Server doesn't respond for a few seconds and then the client gives
the following Error:

Internal Exception: java.net.SocketTimeoutException: Read timed out

I deinstalled all plugins, but it still appears.

**Comment by kitskub** [comment]
What version are you using?

**Comment by kkieslich** [comment]
The newest 1.0. I want to add, that after a few seconds the server is up again without restarting.
This looks to be the same problem ; http://dev.bukkit.org/server-mods/myhungergames/#c1163

**Comment by Trikolon** [comment]
Same issue here. Perhaps that's the time the plugin takes to reset the arena? Somehow it freezes the server.

**Comment by NitroFox0** [comment]
yeah this is true plz plz fix it

**Comment by Trikolon** [comment]
Seems to be fixed in latest dev-build. All fine :)
