### ISSUE TITLE
better tutorials.

### ISSUE THREAD

**Issue by arjove** [kitskub/MyHungerGames#49]
please add more and better tutorials. for example how to create a infowall.

**Comment by NitroFox0** [comment]
You make as many signs as there is spawns in the arena I would suggest if you made them in a square then after you do the infowall commend you just select the points on the square you made out of signs  ( top left corner for the first point then for the second point bottom right corner) sorry for my English I'm polish

**Comment by arjove** [comment]
thanks . forgotten to comment.
