### ISSUE TITLE
[PEX] Perms Not inherited from Parent nodes...

### ISSUE THREAD

**Issue by HelloWorldCool** [kitskub/MyHungerGames#8]
hungergame.admin.\* - gives player perm to initiate cmd: /hga, but cannot do ALL individual commands such as:

/hga add game <game name> <setup name> - create a new game
/hga add spawnpoint <game name> - add a spawnpoint to a game
/hga add chest <game name> - add a chest to a game
/hga add itemset <game name> <itemset name> - add an itemset to a game
/hga remove game <game name> - remove a game
/hga remove spawnpoint <game name> - remove a spawnpoint from a game
/hga remove chest <game name> - remove a chest from a game
/hga set enabled <game name> <true/false> - enable or disable a game
/hga set spawn <game name> - set the spawn for players that die or leave
/hga kick <player> - kick a player from a game
/hga reload - reload plugin
/hga start <game name> <seconds> - manually start a game
/hga pause <game name> - pause a game NOT IMPLEMENTED
/hga resume <game name> <x seconds> - resume a game NOT IMPLEMENTED

Also for hungergame.user.\* it's the same thing.

If i give myself the indivual perm like below, then it works.

hungergame.add.game - create a game
hungergame.add.spawnpoint - add a spawnpoint to a game
hungergame.add.chest - add a chest to a game
hungergame.add.itemset - add an itemset to a game
hungergame.remove.game - remove a game
hungergame.remove.spawnpoint - remove a spawnpoint from a game
hungergame.remove.chest - remove a chest from a game
hungergame.set.enabled - enable or disable a game
hungergame.set.spawn - set the spawn for players that leave or die
hungergame.game.start - manually start a game
hungergame.game.pause - pause start a game NOT IMPLEMENTED
hungergame.game.resume - resume a game NOT IMPLEMENTED
hungergame.admin.reload - reload config and games.yml
hungergame.admin.kick - kick a player from a game
hungergame.admin.help - get admin commands
hungergame.user.join - join a game
hungergame.user.leave - leave a game
hungergame.user.rejoin - rejoin a game
hungergame.user.list - list games
hungergame.user.stat - list stats for a game
hungergame.user.vote - vote that you are ready for a game
hungergame.user.sponsor - sponsor a player an item
hungergame.user.help - get user commands

**Comment by kitskub** [comment]
Are you using the latest version? (Kind of an idiot question, but has to be asked)

**Comment by HelloWorldCool** [comment]
yeah i am, im not complaining or anything just i had to give out all the perms individually.

**Comment by kitskub** [comment]
I'm not sure what is causing the parent nodes not to factor through, but I made a hot-fix which will be in from now on.

**Comment by HelloWorldCool** [comment]
Ok thanks i'll let you know if they work :D

**Comment by kitskub** [comment]
Can I get a confirmation?

**Comment by HelloWorldCool** [comment]
yes i'll test it right now

**Comment by HelloWorldCool** [comment]
The current plugin version 0.4.3, running on Java 7, running on Latest RB, still does not work.

Error Message: "You do not have permission"
Btw remember im using pex.

**Comment by kitskub** [comment]
Gosh dang. It still doesn't work? What gives...

**Comment by HelloWorldCool** [comment]
lol no idea man XD

maybe java 7?

**Comment by kitskub** [comment]
I highly doubt it....its got to be this plugin.yml that @Randude14 wrote... I'll take a second look at it.

**Comment by kitskub** [comment]
Do you use vault?

**Comment by HelloWorldCool** [comment]
i do

**Comment by kitskub** [comment]
This is solved in v0.5-dev. The problem was that it was not "hungergame.admin.*" but instead "hungergame.admin"

**Comment by HelloWorldCool** [comment]
thanks man!
